import { PERMISSIONS } from '../constants/permissions';
import { ROLES } from '../constants/roles';

export const ROLE_PERMISSIONS = {
  [ROLES.ISE]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_BRANCH_DASHBOARD,
    PERMISSIONS.VIEW_PIPELINES,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.VIEW_LEADS_KANBAN,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_SESSIONS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.VIEW_TARGETS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
  ],
  [ROLES.BDE]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_BRANCH_DASHBOARD,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.VIEW_LEADS_KANBAN,
    PERMISSIONS.VIEW_PIPELINES,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_SESSIONS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.VIEW_TARGETS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.VIEW_DAILY_REPORT,
    PERMISSIONS.VIEW_NOTIFICATIONS,
  ],
  [ROLES.BRANCH_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_BRANCH_DASHBOARD,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_BRANCH_SETTINGS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.VIEW_LEADS_KANBAN,
    PERMISSIONS.VIEW_PIPELINES,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_SESSIONS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.VIEW_TARGETS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.APPROVE_TRANSFERS,
    PERMISSIONS.VIEW_TEAM_REPORTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_AUDIT,
  ],
  [ROLES.COMPANY_ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_COMPANY_DASHBOARD,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_COMPANY_SETUP,
    PERMISSIONS.VIEW_BRANCHES,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.MANAGE_ALL_USERS,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.VIEW_LEADS_KANBAN,
    PERMISSIONS.VIEW_PIPELINES,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_SESSIONS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.VIEW_TARGETS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.APPROVE_TRANSFERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.READ_ONLY_REPORTS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_AUDIT,
  ],
  [ROLES.SUPER_ADMIN]: [
    // All permissions
    ...Object.values(PERMISSIONS),
  ],
};

/**
 * Helper to get unique permissions for a list of roles
 */
export const getPermissionsByRoles = (roles = []) => {
  const permissions = new Set();
  roles.forEach((role) => {
    const rolePerms = ROLE_PERMISSIONS[role] || [];
    rolePerms.forEach((perm) => permissions.add(perm));
  });
  return Array.from(permissions);
};
